'use client';
import { useEffect, useMemo, useState } from 'react';
import { addDoc, collection, doc, limit, onSnapshot, orderBy, query, serverTimestamp } from 'firebase/firestore';
import { db, hasFirebaseConfig } from '../lib/firebase';
import { extractTags, generateSvg, sampleMaterials } from '../lib/svg-generator';
const MAX_PROMPT=120;
function formatDate(value){if(!value)return 'サンプル';const date=value.toDate?value.toDate():new Date(value);return new Intl.DateTimeFormat('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(date);}
function downloadSvg(material){const blob=new Blob([material.svg],{type:'image/svg+xml;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${material.title||'hitobito-sozai'}.svg`;a.click();URL.revokeObjectURL(url);}
function downloadPng(material){const blob=new Blob([material.svg],{type:'image/svg+xml;charset=utf-8'});const url=URL.createObjectURL(blob);const image=new Image();image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=1024;const context=canvas.getContext('2d');context.drawImage(image,0,0,1024,1024);URL.revokeObjectURL(url);canvas.toBlob((png)=>{if(!png)return;const pngUrl=URL.createObjectURL(png);const a=document.createElement('a');a.href=pngUrl;a.download=`${material.title||'hitobito-sozai'}.png`;a.click();URL.revokeObjectURL(pngUrl);},'image/png');};image.src=url;}
function MaterialCard({material}){return <article className="material-card"><div className="art" dangerouslySetInnerHTML={{__html:material.svg}}/><div className="card-body"><div className="card-meta"><span>{formatDate(material.publishedAt)}</span><span>{material.isSample?'見本':'NEW'}</span></div><h3>{material.title}</h3><div className="tags">{(material.tags||[]).map((tag)=><span key={tag}>#{tag}</span>)}</div><div className="download-row"><button onClick={()=>downloadSvg(material)}>SVG</button><button onClick={()=>downloadPng(material)}>PNG</button></div></div></article>}
export default function Home(){
 const [prompt,setPrompt]=useState('');const [materials,setMaterials]=useState([]);const [requests,setRequests]=useState([]);const [message,setMessage]=useState('');const [submitting,setSubmitting]=useState(false);
 useEffect(()=>{if(!db)return undefined;const q=query(collection(db,'materials'),orderBy('publishedAt','desc'),limit(36));return onSnapshot(q,(snapshot)=>setMaterials(snapshot.docs.map((item)=>({id:item.id,...item.data()}))));},[]);
 const gallery=useMemo(()=>{const seen=new Set();return [...materials,...sampleMaterials].filter((item)=>{if(seen.has(item.title))return false;seen.add(item.title);return true;});},[materials]);
 async function submit(event){event.preventDefault();const clean=prompt.trim();if(clean.length<3){setMessage('もう少し具体的に書いてください。');return;}setSubmitting(true);setMessage('');
  if(!db){const localId=`demo-${Date.now()}`;setRequests((c)=>[{id:localId,prompt:clean,status:'pending'},...c]);setPrompt('');setMessage('リクエストを受け付けました。デモでは数秒で生成します。');window.setTimeout(()=>{const material={id:localId,requestId:localId,title:clean,prompt:clean,svg:generateSvg(clean,localId),tags:extractTags(clean),publishedAt:new Date()};setMaterials((c)=>[material,...c]);setRequests((c)=>c.map((item)=>item.id===localId?{...item,status:'published'}:item));},6500);setSubmitting(false);return;}
  try{const reference=await addDoc(collection(db,'requests'),{prompt:clean,status:'pending',createdAt:serverTimestamp(),source:'web'});setRequests((c)=>[{id:reference.id,prompt:clean,status:'pending'},...c]);setPrompt('');setMessage('受付完了。通常は数分後にこのページへ掲載されます。');onSnapshot(doc(db,'requests',reference.id),(snapshot)=>{if(!snapshot.exists())return;const data=snapshot.data();setRequests((c)=>c.map((r)=>r.id===reference.id?{...r,status:data.status,reason:data.reason||''}:r));});}catch(error){console.error(error);setMessage('送信できませんでした。設定を確認してください。');}finally{setSubmitting(false);}
 }
 return <main><header className="site-header"><a className="brand" href="#top"><span className="brand-mark">ひ</span><span>ひとびと素材</span></a><div className="header-right"><span className="free-label">商用OKを目指すフリー素材</span>{!hasFirebaseConfig&&<span className="demo-label">デモモード</span>}</div></header>
 <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">みんなの「欲しい」が、次の素材になる。</p><h1>欲しいイラスト、<br/><em>書いてください。</em></h1><p className="lead">リクエストを受け取ると、自動でSVG素材を生成。数分後には、あなたもみんなも使えるフリー素材として並びます。</p><div className="flow"><span>1. リクエスト</span><b>→</b><span>2. 自動生成</span><b>→</b><span>3. みんなに公開</span></div></div>
 <form className="request-box" onSubmit={submit}><label htmlFor="request">どんな素材が欲しいですか？</label><textarea id="request" value={prompt} maxLength={MAX_PROMPT} onChange={(e)=>setPrompt(e.target.value)} placeholder="例：会議で失敗して落ち込んでいる会社員"/><div className="request-footer"><span>{prompt.length}/{MAX_PROMPT}</span><button type="submit" disabled={submitting}>{submitting?'送信中…':'この素材をリクエスト'}</button></div><p className="note">人物・日常・仕事・学校などの一般的な素材向けです。著名人、既存キャラクター、企業ロゴなどは公開しません。</p>{message&&<p className="message">{message}</p>}</form></section>
 {requests.length>0&&<section className="your-requests section-shell"><div className="section-heading"><div><p>YOUR REQUESTS</p><h2>あなたのリクエスト</h2></div><span>この端末で送ったもの</span></div><div className="request-list">{requests.slice(0,4).map((r)=><div className="request-item" key={r.id}><div><strong>{r.prompt}</strong>{r.reason&&<small>{r.reason}</small>}</div><span className={`status ${r.status}`}>{r.status==='published'?'公開済み':r.status==='processing'?'生成中':r.status==='rejected'?'掲載対象外':r.status==='error'?'エラー':'受付済み'}</span></div>)}</div></section>}
 <section className="section-shell gallery-section"><div className="section-heading"><div><p>NEW MATERIALS</p><h2>新着フリー素材</h2></div><span>{gallery.length}点を表示</span></div><div className="gallery">{gallery.map((m)=><MaterialCard key={m.id} material={m}/>)}</div></section>
 <section className="promise section-shell"><div><span>01</span><h3>リクエスト無料</h3><p>「こんな場面が欲しい」を文章で送るだけ。</p></div><div><span>02</span><h3>SVGで軽い</h3><p>拡大してもきれい。Webや資料にも使いやすい形式。</p></div><div><span>03</span><h3>使うほど増える</h3><p>誰かの依頼が、次の誰かに役立つ素材ストックになります。</p></div></section>
 <footer><strong>ひとびと素材</strong><span>sozai.hitobito.jp</span><p>© Hitobito</p></footer></main>;
}
